e2term:
	helm install e2termination e2term -n ricplt

e2manager:
	helm install e2manager e2mgr -n ricplt

dbaas:
	helm install dbaas dbaas -n ricplt

infra:
	helm install infra infrastructure -n ricplt


nms:
	kubectl create ns ricxapp

ricinfra:
	kubectl create ns ricinfra

ves:
	helm install ves vespamgr -n ricplt

submanager:
	helm install submgr submgr -n ricplt

rtmgr:
	helm install rtmgr rtmgr -n ricplt

rtmgr:
	helm install xapp-onboarder xapp-onboarder -n ricplt

redis:
	helm install redis-cluster redis-cluster -n ricplt

a1:
	helm install a1mediator a1mediator -n ricplt

o1:
	helm install o1mediator o1mediator -n ricplt

appmnr:
	helm install appmgr appmgr -n ricplt

jagar:
	helm install jaegeradapter jaegeradapter -n ricplt

alarm-manager:
	helm install alarmmanager alarmmanager -n ricplt

alarm-manager:
	helm install influxdb influxdb -n ricplt